### ISSUE TITLE
pip install django-decorator-include fails with version 0.2

### ISSUE THREAD

**Issue by jdufresne** [jeffkistler/django-decorator-include#2]
```
$ virtualenv test
New python executable in test/bin/python
Installing setuptools, pip...done.

$ test/bin/pip install django-decorator-include
Downloading/unpacking django-decorator-include
  Downloading django-decorator-include-0.2.tar.gz
  Running setup.py (path:/home/jon/test/build/django-decorator-include/setup.py) egg_info for package django-decorator-include

Installing collected packages: django-decorator-include
  Running setup.py install for django-decorator-include
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jon/test/build/django-decorator-include/setup.py", line 33, in <module>
        'Programming Language :: Python :: 3.4',
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/jon/test/lib/python2.7/site-packages/setuptools/command/install.py", line 59, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/jon/test/lib/python2.7/site-packages/setuptools/command/build_py.py", line 42, in run
        self.build_packages()
      File "/usr/lib64/python2.7/distutils/command/build_py.py", line 372, in build_packages
        self.build_module(module, module_file, package)
      File "/home/jon/test/lib/python2.7/site-packages/setuptools/command/build_py.py", line 60, in build_module
        outfile, copied = orig.build_py.build_module(self, module, module_file, package)
      File "/usr/lib64/python2.7/distutils/command/build_py.py", line 333, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple
    Complete output from command /home/jon/test/bin/python -c "import setuptools, tokenize;__file__='/home/jon/test/build/django-decorator-include/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Wb40ls-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jon/test/include/site/python2.7:
    running install

running build

running build_py

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/jon/test/build/django-decorator-include/setup.py", line 33, in <module>

    'Programming Language :: Python :: 3.4',

  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/home/jon/test/lib/python2.7/site-packages/setuptools/command/install.py", line 59, in run

    return orig.install.run(self)

  File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run

    self.run_command('build')

  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run

    self.run_command(cmd_name)

  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/home/jon/test/lib/python2.7/site-packages/setuptools/command/build_py.py", line 42, in run

    self.build_packages()

  File "/usr/lib64/python2.7/distutils/command/build_py.py", line 372, in build_packages

    self.build_module(module, module_file, package)

  File "/home/jon/test/lib/python2.7/site-packages/setuptools/command/build_py.py", line 60, in build_module

    outfile, copied = orig.build_py.build_module(self, module, module_file, package)

  File "/usr/lib64/python2.7/distutils/command/build_py.py", line 333, in build_module

    "'package' must be a string (dot-separated), list, or tuple")

TypeError: 'package' must be a string (dot-separated), list, or tuple

----------------------------------------
Cleaning up...
Command /home/jon/test/bin/python -c "import setuptools, tokenize;__file__='/home/jon/test/build/django-decorator-include/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Wb40ls-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jon/test/include/site/python2.7 failed with error code 1 in /home/jon/test/build/django-decorator-include
Storing debug log for failure in /home/jon/.pip/pip.log
```

**Comment by jdufresne** [comment]
Sorry, wrong repository.
